[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npx serve -s build -l $PORT -d false"

[variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
DISABLE_ESLINT_PLUGIN = "true"
REACT_APP_API_URL = "https://escashop-backend-production.up.railway.app/api"
REACT_APP_SOCKET_URL = "https://escashop-backend-production.up.railway.app"
CI = "false"
# Force Railway to recognize Nixpacks configuration
