[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npx serve -s build -l $PORT"

[variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
DISABLE_ESLINT_PLUGIN = "true"
# Force Railway to recognize Nixpacks configuration
