[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NODE_VERSION = "20"
GENERATE_SOURCEMAP = "false"
DISABLE_ESLINT_PLUGIN = "true"
BUILD_PATH = "build"
PUBLIC_PATH = "/"
INLINE_RUNTIME_CHUNK = "false"
IMAGE_INLINE_SIZE_LIMIT = "0"
REACT_APP_ENABLE_HTTPS = "true"
REACT_APP_ENABLE_DEBUG = "false"
REACT_APP_ENABLE_CONSOLE_LOGS = "false"
REACT_APP_ENABLE_PWA = "false"
REACT_APP_DEFAULT_THEME = "light"
REACT_APP_TIMEZONE = "Asia/Manila"
REACT_APP_LOCALE = "en-PH"
REACT_APP_CURRENCY = "PHP"
REACT_APP_API_TIMEOUT = "30000"
REACT_APP_MAX_RETRIES = "3"
REACT_APP_WS_RECONNECT_DELAY = "5000"
REACT_APP_WS_MAX_RECONNECT_ATTEMPTS = "10"
REACT_APP_ENABLE_SERVICE_WORKER = "true"
REACT_APP_CACHE_ASSETS = "true"
# REACT_APP_API_URL will be set in Railway dashboard to point to backend service
