version: '3.8'

services:
  # PostgreSQL Database (same as production)
  postgres:
    image: postgres:15-alpine
    container_name: escashop-postgres-dev
    environment:
      POSTGRES_DB: escashop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - escashop-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend Service with Development Hot-Reloading
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: escashop-backend-dev
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=escashop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/escashop
      - JWT_SECRET=dev-jwt-secret-key
      - JWT_REFRESH_SECRET=dev-jwt-refresh-secret-key
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    networks:
      - escashop-dev-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: npm run dev

  # Frontend Service with Development Hot-Reloading
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
      args:
        - REACT_APP_API_URL=http://localhost:5000
        - REACT_APP_SOCKET_URL=http://localhost:5000
        - NODE_ENV=development
    container_name: escashop-frontend-dev
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_SOCKET_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    networks:
      - escashop-dev-network
    depends_on:
      - backend-dev
    restart: unless-stopped
    command: npm start

# Volumes
volumes:
  postgres_dev_data:
    driver: local

# Networks
networks:
  escashop-dev-network:
    driver: bridge
