[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
PORT = "5000"
JWT_EXPIRES_IN = "30m"
JWT_REFRESH_EXPIRES_IN = "7d"
SESSION_TIMEOUT = "3600000"
SMS_PROVIDER = "vonage"
SMS_ENABLED = "true"
SMS_FROM = "EscaShop"
EMAIL_SERVICE_ENABLED = "true"
EMAIL_SERVICE = "gmail"
TZ = "Asia/Manila"
LOG_LEVEL = "info"
WEBSOCKET_ENABLED = "true"
DEFAULT_PAGE_SIZE = "20"
MAX_PAGE_SIZE = "100"
AVERAGE_SERVICE_TIME = "15"
PRIORITY_BOOST = "1000"
RATE_LIMIT_WINDOW = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
BCRYPT_SALT_ROUNDS = "12"
PASSWORD_MIN_LENGTH = "8"
BACKUP_RETENTION_DAYS = "30"
DB_POOL_MIN = "2"
DB_POOL_MAX = "20"
DB_POOL_IDLE_TIMEOUT = "30000"
DB_POOL_CONNECTION_TIMEOUT = "60000"
HEALTH_CHECK_ENABLED = "true"
METRICS_ENABLED = "true"
ENABLE_UNIQUE_SETTLEMENT_INDEX = "true"
ENABLE_SETTLEMENT_TRACING = "true"
ENABLE_SETTLEMENT_MONITORING = "true"
ENABLE_CSRF_PROTECTION = "true"
ENABLE_HELMET_SECURITY = "true"
SECURE_COOKIES = "true"
MAX_FILE_SIZE = "5242880"
UPLOAD_PATH = "./uploads"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s build -l $PORT"

[services.variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
DISABLE_ESLINT_PLUGIN = "true"
BUILD_PATH = "build"
PUBLIC_PATH = "/"
INLINE_RUNTIME_CHUNK = "false"
IMAGE_INLINE_SIZE_LIMIT = "0"
REACT_APP_ENABLE_HTTPS = "true"
REACT_APP_ENABLE_DEBUG = "false"
REACT_APP_ENABLE_CONSOLE_LOGS = "false"
REACT_APP_ENABLE_PWA = "false"
REACT_APP_DEFAULT_THEME = "light"
REACT_APP_TIMEZONE = "Asia/Manila"
REACT_APP_LOCALE = "en-PH"
REACT_APP_CURRENCY = "PHP"
REACT_APP_API_TIMEOUT = "30000"
REACT_APP_MAX_RETRIES = "3"
REACT_APP_WS_RECONNECT_DELAY = "5000"
REACT_APP_WS_MAX_RECONNECT_ATTEMPTS = "10"
REACT_APP_ENABLE_SERVICE_WORKER = "true"
REACT_APP_CACHE_ASSETS = "true"
