[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Force rebuild to pick up latest package.json start script - v2

[env]
NODE_ENV = "production"
NODE_VERSION = "20"
PORT = "5000"

# Database will be automatically injected by Railway PostgreSQL service
# JWT Secrets - SET THESE IN RAILWAY DASHBOARD
# JWT_SECRET = "your-jwt-secret"
# JWT_REFRESH_SECRET = "your-jwt-refresh-secret"

# Application Configuration
JWT_EXPIRES_IN = "30m"
JWT_REFRESH_EXPIRES_IN = "7d"
SESSION_TIMEOUT = "3600000"
SMS_PROVIDER = "vonage"
SMS_ENABLED = "true"
SMS_FROM = "EscaShop"
EMAIL_SERVICE_ENABLED = "true"
EMAIL_SERVICE = "gmail"
TZ = "Asia/Manila"
LOG_LEVEL = "info"
WEBSOCKET_ENABLED = "true"
DEFAULT_PAGE_SIZE = "20"
MAX_PAGE_SIZE = "100"
AVERAGE_SERVICE_TIME = "15"
PRIORITY_BOOST = "1000"
RATE_LIMIT_WINDOW = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
BCRYPT_SALT_ROUNDS = "12"
PASSWORD_MIN_LENGTH = "8"
BACKUP_RETENTION_DAYS = "30"
DB_POOL_MIN = "2"
DB_POOL_MAX = "20"
DB_POOL_IDLE_TIMEOUT = "30000"
DB_POOL_CONNECTION_TIMEOUT = "60000"
HEALTH_CHECK_ENABLED = "true"
METRICS_ENABLED = "true"
ENABLE_UNIQUE_SETTLEMENT_INDEX = "true"
ENABLE_SETTLEMENT_TRACING = "true"
ENABLE_SETTLEMENT_MONITORING = "true"
ENABLE_CSRF_PROTECTION = "true"
ENABLE_HELMET_SECURITY = "true"
SECURE_COOKIES = "true"
MAX_FILE_SIZE = "5242880"
UPLOAD_PATH = "./uploads"
